// <auto-generated />
using System;
using Infra.Data.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Domain.Models.EmprestimoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data-devolucao");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("TEXT")
                        .HasColumnName("data-emprestimo");

                    b.Property<int>("LivroId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("livro-id");

                    b.Property<int>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("emprestimos", (string)null);
                });

            modelBuilder.Entity("Domain.Models.LivroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("autor");

                    b.Property<short>("QuantidadeDisponivel")
                        .HasColumnType("smallint")
                        .HasColumnName("quantidade-disponivel");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("livros", (string)null);
                });

            modelBuilder.Entity("Domain.Models.EmprestimoModel", b =>
                {
                    b.HasOne("Domain.Models.LivroModel", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });
#pragma warning restore 612, 618
        }
    }
}
